---
swagger: "2.0"
info:
  description: "CMAQ Exposure API"
  version: "1.0.0"
  title: "CMAQ Exposure API"
  termsOfService: "None"
  contact:
    name: "Michael J. Stealey"
    url: "https://github.com/renci/cmaq-exposure-api"
    email: "stealey@renci.org"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "cmaq-dev.edc.renci.org"
basePath: "/v1"
schemes:
- "https"
paths:
  /variables:
    get:
      summary: "CMAQ exposure variables"
      description: "CMAQ exposure variables"
      operationId: "controllers.default_controller.variables_get"
      produces:
      - "application/json"
      parameters:
      - name: "search"
        in: "query"
        description: "search for exposure variable like - default is empty"
        required: false  
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid parameter"
        404:
          description: "No exposure types found"
        500:
          description: "Server error"
  /values:
    get:
      summary: "get values for exposure variable at location for date range"
      description: "get values for exposure variable at location for date range"
      operationId: "controllers.default_controller.values_get"
      produces:
      - "application/json"
      parameters:
      - name: "variable"
        in: "query"
        description: "cmaq variable - one or more seperated by ;"
        required: true
        type: "string"
      - name: "start_date"
        in: "query"
        description: "start date of range"
        required: true
        type: "string"
        format: "date"
      - name: "end_date"
        in: "query"
        description: "end date of range"
        required: true
        type: "string"
        format: "date"
      - name: "lat_lon"
        in: "query"
        description: "latitude,longitude - one or more pairs seperated by ;"
        required: true
        type: "string"
      - name: "resolution"
        in: "query"
        description: "temporal resolution (hour, day, 7day, 14day) - default is day"
        required: false
        type: "string"
        default: "day"
      - name: "aggregation"
        in: "query"
        description: "numerical aggregation (max, avg) - default is max"
        required: false
        type: "string"
        default: "max"
      - name: "utc_offset"
        in: "query"
        description: "timezone offset from UTC (utc, eastern, central, mountain, pacific)\
          \ - default is utc"
        required: false
        type: "string"
        default: "utc"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid parameter"
        404:
          description: "No values found"
        500:
          description: "Server error"
definitions:
  inline_response_200_1_cmaq_output:
    properties:
      date_time:
        type: "string"
        format: "date-time"
        example: "2010-01-01 00:00:00"
      value:
        type: "number"
        format: "float"
        example: 49.819595
      quality_metric:
        $ref: "#/definitions/inline_response_200_1_quality_metric"
    example:
      date_time: "2010-01-01 00:00:00"
      quality_metric:
        mod_mean: 31.6488
        obs_mean: 18.1636
        mb: 13.4852
        cor: 0.54
        rmse: 18.7292
      value: 49.819595
  inline_response_200_1_quality_metric:
    properties:
      cor:
        type: "number"
        format: "float"
        example: 0.54
      mb:
        type: "number"
        format: "float"
        example: 13.4852
      mod_mean:
        type: "number"
        format: "float"
        example: 31.6488
      obs_mean:
        type: "number"
        format: "float"
        example: 18.1636
      rmse:
        type: "number"
        format: "float"
        example: 18.7292
    example:
      mod_mean: 31.6488
      obs_mean: 18.1636
      mb: 13.4852
      cor: 0.54
      rmse: 18.7292
  inline_response_200_1_values:
    properties:
      variable:
        type: "string"
        example: "o3"
      lat_lon:
        type: "string"
        example: "35,-80"
      cmaq_output:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_1_cmaq_output"
    example:
      variable: "o3"
      cmaq_output:
      - date_time: "2010-01-01 00:00:00"
        quality_metric:
          mod_mean: 31.6488
          obs_mean: 18.1636
          mb: 13.4852
          cor: 0.54
          rmse: 18.7292
        value: 49.819595
      - date_time: "2010-01-01 00:00:00"
        quality_metric:
          mod_mean: 31.6488
          obs_mean: 18.1636
          mb: 13.4852
          cor: 0.54
          rmse: 18.7292
        value: 49.819595
      lat_lon: "35,-80"
  inline_response_200_1:
    properties:
      values:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_1_values"
    example:
      values:
      - variable: "o3"
        cmaq_output:
        - date_time: "2010-01-01 00:00:00"
          quality_metric:
            mod_mean: 31.6488
            obs_mean: 18.1636
            mb: 13.4852
            cor: 0.54
            rmse: 18.7292
          value: 49.819595
        lat_lon: "35,-80"
  inline_response_200:
    properties:
      variables:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_variables"
    example:
      variables:
      - utc_max_date_time: "2010-12-31 23:00:00"
        variable: "o3"
        quality_metric:
        - variable: "rmse"
          common_name: "root mean squared error"
        description: "1000.0*O3[1]"
        has_quality_metric: true
        aggregation:
        - "avg;max"
        units: "ppbV"
        common_name: "ozone"
        utc_min_date_time: "2010-01-01 00:00:00"
        resolution:
        - "hour;day;7day;14day"
  inline_response_200_variables:
    properties:
      variable:
        type: "string"
        example: "o3"
      description:
        type: "string"
        example: "1000.0*O3[1]"
      has_quality_metric:
        type: "boolean"
        example: true
      quality_metric:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_quality_metric"
      units:
        type: "string"
        example: "ppbV"
      common_name:
        type: "string"
        example: "ozone"
      utc_min_date_time:
        type: "string"
        format: "date-time"
        example: "2010-01-01 00:00:00"
      utc_max_date_time:
        type: "string"
        format: "date-time"
        example: "2010-12-31 23:00:00"
      resolution:
        type: "array"
        items:
          type: "string"
          example: "hour;day;7day;14day"
      aggregation:
        type: "array"
        items:
          type: "string"
          example: "avg;max"
    example:
      utc_max_date_time: "2010-12-31 23:00:00"
      variable: "o3"
      quality_metric:
      - variable: "rmse"
        common_name: "root mean squared error"
      description: "1000.0*O3[1]"
      has_quality_metric: true
      aggregation:
      - "avg;max"
      units: "ppbV"
      common_name: "ozone"
      utc_min_date_time: "2010-01-01 00:00:00"
      resolution:
      - "hour;day;7day;14day"
  inline_response_200_quality_metric:
    properties:
      common_name:
        type: "string"
        example: "root mean squared error"
      variable:
        type: "string"
        example: "rmse"
    example:
      variable: "rmse"
      common_name: "root mean squared error"
parameters:
  search:
    name: "search"
    in: "query"
    description: "search for exposure variable like - default is empty"
    required: false
    type: "string"
  variable:
    name: "variable"
    in: "query"
    description: "cmaq variable - one or more seperated by ;"
    required: true
    type: "string"
  start_date:
    name: "start_date"
    in: "query"
    description: "start date of range"
    required: true
    type: "string"
    format: "date"
  end_date:
    name: "end_date"
    in: "query"
    description: "end date of range"
    required: true
    type: "string"
    format: "date"
  lat_lon:
    name: "lat_lon"
    in: "query"
    description: "latitude,longitude - one or more pairs seperated by ;"
    required: true
    type: "string"
  resolution:
    name: "resolution"
    in: "query"
    description: "temporal resolution (hour, day, 7day, 14day) - default is day"
    required: false
    type: "string"
    default: "day"
  aggregation:
    name: "aggregation"
    in: "query"
    description: "numerical aggregation (max, avg) - default is max"
    required: false
    type: "string"
    default: "max"
  utc_offset:
    name: "utc_offset"
    in: "query"
    description: "timezone offset from UTC (utc, eastern, central, mountain, pacific)\
      \ - default is utc"
    required: false
    type: "string"
    default: "utc"
